### PR TITLE
Drag & drop for modifier list

### PR DESCRIPTION
**Pull request by amb**
Probably still some bugs. Most obvious things should be fixed. Requires more eyes and possibly testing. You're free to pick & choose things you like or don't like. Regards.

### CODE REVIEW

**Comment by Symstract** [comment]
Thanks for your work! Here's some feedback:

- It shouldn't require a click, it should be: press: start dragging, release: stop dragging. If event.type == 'LEFTMOUSE' and event.value == 'CLICK_DRAG' should work?
- Clicking without moving mouse should still select the modifier if possible.
- It doesn't work properly in the sidebar or in the popup. It can be disabled inside them for now if it's hard to make it work inside them. Can be tackled later, after merge.
- Would be good to make it work also when the list is reversed, but it can also be done later.
- The drawing area could be limited by the number of modifiers, so the line wouldn't move all the way to the bottom of the editor . (It doesn't work if all modifier don't fit in the view, though.)
- Using a custom shader seems like overkill for this. Using gpu.shader.from_builtin('2D_UNIFORM_COLOR') would be simpler?

I don't know if you want to continue working on this or not, but if not, I can continue this at some point.

**Comment by amb** [comment]
* As far as I know, you can't start an operator with just mouse down, it has to be mouse click. What you described would be the best solution though.
* This issue is the same as the above one, it's a limitation of the Blender Python API
* True, I will disable those
* Yes, that remains to be done
* I'll make the changes to limit it to number of modifiers.  Would be nice if there was also a way to limit it to the list view size, but haven't yet found one.
* Custom shader is because the GL uniforms for X and Y, which the builtin shader doesn't support. So that the vertex data doesn't have to be rebuilt each frame of the modal operator, only the uniform has to be changed. Builtin operator is basically the same thing, it just has less options.

**Comment by Symstract** [comment]
- Ah, of course it needs to be a click... I didn't think.
- About the custom shader: Ok, then it's fine. I should learn GL in the future.

About latest commits:
- Wow, that hack works! I probably wouldn't have realized that's possible to do.
- Why the change to double quotes?  Single quotes are used in Blender for enum items and I've used the same style for the icons as well.

Btw, it could be nice if the line would always initially be below the moving modifier. Currently it can be above or below. And if you drag up, the line would skip the first gap, because that doesn't count. Or would that just complicate the code for little benefit?

**Comment by amb** [comment]
It's https://github.com/psf/black, I have bind it to shortcut and it was an accidental click that I didn't notice. I can revert that if needed.

The logic with the line currently is that it shows where the modifier will be positioned when moved and the position will be determined by mouse location. Pretty simple. Sure, if there are better workflows it can be changed. Probably would focus on the D&D also for the popup and side panel first.

**Comment by Symstract** [comment]
Ah, I see. I was wondering why you included that. I'd prefer it to be reverted.

I meant this:
DnD behaviour

But yea, better to focus on more important things.

**Comment by Symstract** [comment]
Closing this since this isn't being developed anymore. Scrolling the properties editor causes it not to work and it doesn't work in the popup or in the sidebar, etc. Thanks for trying it.

**Pull request closed without merging**
